USER=ybong
PATH=/Users/ybong/.brew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Users/ybong/.brew/bin
LOGNAME=ybong
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.NehgjjotKR/Listeners
HOME=/Users/ybong
SHELL=/bin/zsh
__CF_USER_TEXT_ENCODING=0x19040:0x0:0x0
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n000ch80003420/T/
XPC_SERVICE_NAME=0
XPC_FLAGS=0x0
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
SHLVL=1
PWD=/Users/ybong/goinfre/minishell
OLDPWD=/Users/ybong/goinfre
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.57.1
LANG=en_US.UTF-8
COLORTERM=truecolor
VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n000ch80003420/T/vscode-git-39afc66ed8.sock
GIT_ASKPASS=/private/var/folders/zz/zyxvpxvq6csfxvn_n000ch80003420/T/AppTranslocation/FAEEFF4A-E0EC-455A-8FAD-DCA32E1F6353/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
VSCODE_GIT_ASKPASS_NODE=/private/var/folders/zz/zyxvpxvq6csfxvn_n000ch80003420/T/AppTranslocation/FAEEFF4A-E0EC-455A-8FAD-DCA32E1F6353/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)
VSCODE_GIT_ASKPASS_MAIN=/private/var/folders/zz/zyxvpxvq6csfxvn_n000ch80003420/T/AppTranslocation/FAEEFF4A-E0EC-455A-8FAD-DCA32E1F6353/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
TERM=xterm-256color
_=/Users/ybong/goinfre/minishell/./minishell
